### ISSUE TITLE
Alias on local build assumed?

### ISSUE THREAD

**Issue by claytron** [tomster/git-svn-helpers#2]
Here is what I ran

```
$ svn co http://svn/my/repo/project/trunk my_project
$ cd my_project
$ gitify
Git branch 'local/trunk' is now following svn branch 'trunk':
git: 'st' is not a git-command. See 'git --help'.

Did you mean one of these?
        reset
        stage
        stash
        svn
```

I'm assuming that you have an alias set up for `git st`

**Comment by tomster** [comment]
Thanks for posting this, Claytron! I only saw it today, I should set up notifications for issues, I guess.

I've fixed it on master and will make a release soonish™
