### ISSUE TITLE
gitification of "full" svn repo fails

### ISSUE THREAD

**Issue by chaoflow** [tomster/git-svn-helpers#3]
gitify does not know how to handle svn checkouts with trunk/tags/branches subdirs (see below).

I am not sure whether it should be and how it should handle it.

22:23:33 <master> marvin:~/devel/mrd/repos/example.svnprojectrepo/
% gitify 
Unrecognized svn structure!

22:23:37 <master> marvin:~/devel/mrd/repos/example.svnprojectrepo/
1 % ls -la
total 0K
drwxr-xr-x 6 cfl cfl  55 2009-10-31 14:38 ./
drwxr-xr-x 6 cfl cfl 116 2009-10-31 20:29 ../
drwxr-xr-x 6 cfl cfl  92 2009-10-31 14:38 .svn/
drwxr-xr-x 3 cfl cfl  17 2009-10-31 14:38 branches/
drwxr-xr-x 3 cfl cfl  17 2009-10-31 14:38 tags/
drwxr-xr-x 5 cfl cfl  64 2009-10-31 14:38 trunk/

22:23:47 <master> marvin:~/devel/mrd/repos/example.svnprojectrepo/
1 % cd trunk
22:23:50 <master> marvin:~/devel/mrd/repos/example.svnprojectrepo/trunk/
% ls -la
total 0K
drwxr-xr-x 5 cfl cfl 64 2009-10-31 14:38 ./
drwxr-xr-x 6 cfl cfl 55 2009-10-31 14:38 ../
drwxr-xr-x 6 cfl cfl 92 2009-10-31 14:38 .svn/
drwxr-xr-x 4 cfl cfl 59 2009-10-31 14:38 example.svnprojectrepo.pkg1/
drwxr-xr-x 4 cfl cfl 51 2009-10-31 14:38 subdir/

22:23:54 <master> marvin:~/devel/mrd/repos/example.svnprojectrepo/trunk/
% gitify 
No git repository found in /home/cfl/.gitcache/.
Initiating cloning into cache.
Analyzing svn log...
Cloning https://svn.plone.org/svn/collective/example.svnprojectrepo/ from r100499:100499 into /home/cfl/.gitcache/
Initialized empty Git repository in /home/cfl/.gitcache/example.svnprojectrepo/.git/
Using higher level of URL: https://svn.plone.org/svn/collective/example.svnprojectrepo => https://svn.plone.org/svn/collective
    A   subdir/example.svnprojectrepo.pkg2/.gitignore
    A   subdir/example.svnprojectrepo.pkg2/setup.py
    A   subdir/example.svnprojectrepo.pkg2/src/example/svnprojectrepo/pkg2/**init**.py
    A   subdir/example.svnprojectrepo.pkg2/src/example/svnprojectrepo/**init**.py
    A   subdir/example.svnprojectrepo.pkg2/src/example/**init**.py
    A   example.svnprojectrepo.pkg1/.gitignore
    A   example.svnprojectrepo.pkg1/setup.py
    A   example.svnprojectrepo.pkg1/src/example/svnprojectrepo/pkg1/**init**.py
    A   example.svnprojectrepo.pkg1/src/example/svnprojectrepo/**init**.py
    A   example.svnprojectrepo.pkg1/src/example/**init**.py
r100499 = 16a2c53cd3dc28e6cc037ca0f9a05da4cd2c9f0c (refs/remotes/trunk)
Checked out HEAD:
  https://svn.plone.org/svn/collective/example.svnprojectrepo/trunk r100499
Traceback (most recent call last):
  File "/usr/bin/gitify", line 8, in <module>
    load_entry_point('git-svn-helpers==0.5', 'console_scripts', 'gitify')()
  File "/usr/lib/python2.6/site-packages/git_svn_helpers-0.5-py2.6.egg/gitsvnhelpers/gitify.py", line 153, in **call**
    self.commands.get(command, self.unknown)()
  File "/usr/lib/python2.6/site-packages/git_svn_helpers-0.5-py2.6.egg/gitsvnhelpers/gitify.py", line 58, in **call**
    os.chdir(config.GIT_CACHE + package_name)
OSError: [Errno 2] No such file or directory: '/home/cfl/.gitcache/trunk'

**Comment by tomster** [comment]
Basically, this is by design. The starting point is always a local checkout of an svn repository at either trunk or at a branch. gitify will then use that information to clone the _full_ repository.

supporting multiple 'entry points' would just make the code more complicated with little gain for the end-user IMO.
