### ISSUE TITLE
gitify swallowing error conditions / prompts

### ISSUE THREAD

**Issue by davidblewett** [tomster/git-svn-helpers#4]
Just ran into a problem where I'd accidentally done a svn up before running gitify up. I couldn't figure out why the process kept sitting there and never finishing, until I hit Ctl-C and saw that the `git svn rebase` operation had thrown an error:

error: Untracked working tree file 'foo.pt' would be overwritten by merge.

I did a git reset --hard remotes/trunk , and then gitify up was able to finish fine. I'm concerned that gitify is swallowing error conditions with no indication. I have a co-worker that ran into a similar issue, where gitify up was swallowing prompts for the svn password with no indication of what was wrong.

**Comment by tomster** [comment]
hi david,

thanks for the report. there is obviously something wrong and i'll look into it ASAP. gitify should _never_ swallow any errors, it's an explicit design decision to not be intrusive or 'sneaky'.

**Comment by tomster** [comment]
david, i've tried to reproduce the issue but so-far gitify works as expected.

can you take a look at the test i created at http://github.com/tomster/git-svn-helpers/commit/0e01986a7a698e9fd517d1ced3ae1d0d59de7499 and help out what else you did, so we can reproduce your issue?

**Comment by do3cc** [comment]
I have a similar issue.
gitify does not block, but the error gets swallowed too. 
I run the classic buildout plone with mr.developer checkouts. When doing svn log, I saw changes up to today, when doing gitfy up, I saw changes up to the beginning of this month.
A manual git stash;git svn rebase;git stash apply gave me the same error david mentioned. after deleting the file, update works again.

I try to make buildouts for all eggs, so I gitified the package as a svn checkout much earlier, and only today I checked out the package itself with svn, and did the gitify init. 

I understood your testcase, but I could also not see, why it should work there and not here.

I had the issue several times already, and never remembered what I did. But I was swearing a lot ;-).

Next time I notice something odd, I will take a closer look, and if you don't mind, ask for help if I see you in irc. Or I ask chaoflow, you should have brought him up to speed I hope ;-)

**Comment by tomster** [comment]
i assume it's an issue with how i use mkrelease's popen statement to run the git-svn command. i will a) ask stefan (the author) about it and b) perhaps you guys have some suggestions on how to better run the external commands?

**Comment by davidblewett** [comment]
Sorry it's taken me a bit to reply. Haven't had much spare time to look into this. I'll try to set aside some time to help troubleshoot later this week.
